### ISSUE TITLE
Copy code into Search Labs

### ISSUE THREAD

**Issue by serenachou** [salgado/music-search#1]
Hi @salgado  Phillipp has flagged that we would like to bring your blog over into Search Labs. We'd love for you to also move this code into https://github.com/elastic/elasticsearch-labs if you don't mind! :)

**Comment by serenachou** [comment]
This ticket would be for us to update the merged code that you'll provide with the migrated blog: https://github.com/elastic/elasticsearch-labs/issues/87

**Comment by salgado** [comment]
Ok, I will move it. Is there any convention? Is there a specific folder to move or rename it to?

**Comment by serenachou** [comment]
by the way, I think there will be a bit of delay in the migration of the blog so feel free to just make a copy of this available in Search Labs! You can add a folder under https://github.com/elastic/elasticsearch-labs/tree/main/supporting-blog-content

**Comment by salgado** [comment]
@serenachou,  I sent you a PR ready to merge, https://github.com/elastic/elasticsearch-labs/pull/93

**Comment by serenachou** [comment]
Thank you sir!
